name: learn-gh-actions
on: [push]
jobs:
    my-job:
        runs-on: ubuntu-latest
	steps:
	    - uses: actions/checkout@v2
	    - run: echo "Good morning"
	    - run: ls -l
	    - run: echo "Good night"