name: learn-gh-actions
on: [push]
jobs:
    my-job:
    
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
  
        - name: Welcome
          run: echo "Good morning"

        - name: Do some work
          run: ls -l

        - name: Cleanup
          run: echo "Good night"